In [39]:
import pandas as pd
import numpy as np

In [40]:
data = pd.read_csv('Iris.csv')
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [41]:
attribute = np.array(data)[:, :]

In [42]:
attribute

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa'],
       [5.0, 3.6, 1.4, 0.2, 'setosa'],
       [5.4, 3.9, 1.7, 0.4, 'setosa'],
       [4.6, 3.4, 1.4, 0.3, 'setosa'],
       [5.0, 3.4, 1.5, 0.2, 'setosa'],
       [4.4, 2.9, 1.4, 0.2, 'setosa'],
       [4.9, 3.1, 1.5, 0.1, 'setosa'],
       [5.4, 3.7, 1.5, 0.2, 'setosa'],
       [4.8, 3.4, 1.6, 0.2, 'setosa'],
       [4.8, 3.0, 1.4, 0.1, 'setosa'],
       [4.3, 3.0, 1.1, 0.1, 'setosa'],
       [5.8, 4.0, 1.2, 0.2, 'setosa'],
       [5.7, 4.4, 1.5, 0.4, 'setosa'],
       [5.4, 3.9, 1.3, 0.4, 'setosa'],
       [5.1, 3.5, 1.4, 0.3, 'setosa'],
       [5.7, 3.8, 1.7, 0.3, 'setosa'],
       [5.1, 3.8, 1.5, 0.3, 'setosa'],
       [5.4, 3.4, 1.7, 0.2, 'setosa'],
       [5.1, 3.7, 1.5, 0.4, 'setosa'],
       [4.6, 3.6, 1.0, 0.2, 'setosa'],
       [5.1, 3.3, 1.7, 0.5, 'setosa'],
       [4.8, 3.4, 1.9, 0.2, 'setosa'],
       [5.0, 3.0, 1.6, 0.

In [43]:
#get distance from two coordinate
def getEuclidean(coordinate1,coordinate2):
    distance = 0
    for i in range(len(coordinate2)-1):
        distance += pow((coordinate1[i]-coordinate2[i]),2)
    return pow(distance,0.5)

In [44]:
def getNeighbour(dataTest, dataTraining):
    length = len(dataTraining)
    distances = []
    for i in range(length):
        dist = getEuclidean(dataTest, dataTraining[i])
        distances.append((dist, dataTraining[i][-1]))
    
    distances.sort(key = lambda x:x[0])
    return distances

In [45]:
def splitDataTest(start, end, data):
    test = []
    
    while(start < end):
        test.append(data[start])
        start+=1
    return test

In [46]:
def splitDataTraining(startIndex, endIndex, data):
    dataTraining = []
    
    if(startIndex == 0):
        temp = data[endIndex:]
        for i in range(len(temp)):
            dataTraining.append(temp[i])
            
    elif(endIndex == len(data)):
        temp = data[:startIndex]
        for i in range(len(temp)):
            dataTraining.append(temp[i])
            
    else:
        temp = data[:startIndex]
        for i in range(len(temp)):
            dataTraining.append(temp[i])
        
        temp = data[endIndex:]
        for i in range(len(temp)):
            dataTraining.append(temp[i])
        
    return dataTraining

In [75]:
k = 10
lengthEksperimen = 100 // k
lengthData = len(attribute) * k // 100 
startIndex = 0
endIndex = lengthData
dataTest = []
dataTrain = []

for i in range(lengthEksperimen):
    dataTest.append(splitDataTest(startIndex, endIndex, attribute))
    dataTrain.append(splitDataTraining(startIndex, endIndex, attribute))
    
    startIndex+=lengthData
    endIndex+=lengthData


In [76]:
len(dataTest[0])

15

In [77]:
len(dataTrain[0])

135

In [78]:
neighbour=[]
for i in range(len(dataTest)):
    for j in range(len(dataTest[i])):
        temp = getNeighbour(dataTest[i][j], dataTrain[i])
        neighbour.append(temp)


In [79]:
neighbour[0]

[(0.09999999999999998, 'setosa'),
 (0.14142135623730964, 'setosa'),
 (0.14142135623730995, 'setosa'),
 (0.14142135623730995, 'setosa'),
 (0.17320508075688743, 'setosa'),
 (0.22360679774997896, 'setosa'),
 (0.30000000000000016, 'setosa'),
 (0.30000000000000027, 'setosa'),
 (0.316227766016838, 'setosa'),
 (0.33166247903553986, 'setosa'),
 (0.3605551275463989, 'setosa'),
 (0.37416573867739383, 'setosa'),
 (0.3872983346207423, 'setosa'),
 (0.41231056256176635, 'setosa'),
 (0.4358898943540679, 'setosa'),
 (0.45825756949558394, 'setosa'),
 (0.4690415759823426, 'setosa'),
 (0.4690415759823426, 'setosa'),
 (0.46904157598234303, 'setosa'),
 (0.53851648071345, 'setosa'),
 (0.5385164807134504, 'setosa'),
 (0.5477225575051662, 'setosa'),
 (0.5477225575051664, 'setosa'),
 (0.58309518948453, 'setosa'),
 (0.5916079783099616, 'setosa'),
 (0.5916079783099616, 'setosa'),
 (0.6164414002968975, 'setosa'),
 (0.6244997998398396, 'setosa'),
 (0.648074069840786, 'setosa'),
 (0.7416198487095667, 'setosa'),
 (0

In [80]:
def separateByClass(attribute):
    separated = {}
    for i in range(len(attribute)):
        vector = attribute[i]
        if (vector[-1] not in separated):
            separated[vector[-1]] = []
        separated[vector[-1]].append(vector)
    
    copy = list(separated)
    return copy

In [81]:
getClass = separateByClass(attribute)

In [82]:
getClass

['setosa', 'versicolor', 'virginica']

In [83]:
total = 0
total2 = 0
total3 = 0
hasil = []

for i in range(len(neighbour)):
    for j in range(k):
        if(neighbour[i][j][-1] == getClass[0]):
            total += 1            
        elif(neighbour[i][j][-1] == getClass[1]):
            total2 += 1
        elif(neighbour[i][j][-1] == getClass[2]):
            total3 += 1
    
    if(total >= total2 and total >= total3):
        hasil.append((getClass[0], total))
    elif(total2 >= total and total2 >= total3):
        hasil.append((getClass[1], total2))
    elif(total3 >= total and total3 >= total2):
        hasil.append((getClass[2], total3))
    
    total = 0
    total2 = 0
    total3 = 0

In [84]:
hasil[0]

('setosa', 10)

In [85]:
startIndex = 0
endIndex = lengthData
splitResult = []

for i in range(lengthEksperimen):
    splitResult.append(splitDataTest(startIndex, endIndex, hasil))
    startIndex+=lengthData
    endIndex+=lengthData

In [86]:
splitResult[1]

[('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10),
 ('setosa', 10)]

In [87]:
dataTest[9]

[array([7.7, 3.0, 6.1, 2.3, 'virginica'], dtype=object),
 array([6.3, 3.4, 5.6, 2.4, 'virginica'], dtype=object),
 array([6.4, 3.1, 5.5, 1.8, 'virginica'], dtype=object),
 array([6.0, 3.0, 4.8, 1.8, 'virginica'], dtype=object),
 array([6.9, 3.1, 5.4, 2.1, 'virginica'], dtype=object),
 array([6.7, 3.1, 5.6, 2.4, 'virginica'], dtype=object),
 array([6.9, 3.1, 5.1, 2.3, 'virginica'], dtype=object),
 array([5.8, 2.7, 5.1, 1.9, 'virginica'], dtype=object),
 array([6.8, 3.2, 5.9, 2.3, 'virginica'], dtype=object),
 array([6.7, 3.3, 5.7, 2.5, 'virginica'], dtype=object),
 array([6.7, 3.0, 5.2, 2.3, 'virginica'], dtype=object),
 array([6.3, 2.5, 5.0, 1.9, 'virginica'], dtype=object),
 array([6.5, 3.0, 5.2, 2.0, 'virginica'], dtype=object),
 array([6.2, 3.4, 5.4, 2.3, 'virginica'], dtype=object),
 array([5.9, 3.0, 5.1, 1.8, 'virginica'], dtype=object)]

In [88]:
error = 0
hasilError = []

for i in range(lengthEksperimen):
    for j in range(lengthData):
        if(dataTest[i][j][-1] != splitResult[i][j][0]):
            error +=1
    message = "Hasil Error :"
    hasilError.append(error/len(attribute)*100)
    error = 0
    

In [89]:
hasilError[9]

0.6666666666666667

In [90]:
testPrint = np.array(dataTest)
resultPrint = np.array(splitResult)

In [63]:
for i in range(lengthEksperimen):
    print("======================================================")
    print("\nEksperimen ", i+1, " : ")
    print("\nHasil K-NN : ")
    print(resultPrint[i])
    print("\nData Test & Hasil Sebenarnya : ")
    print(testPrint[i])
    print("\nHasil Error : ", hasilError[i])
    print("")
    print("======================================================")


Eksperimen  1  : 

Hasil K-NN : 
[['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']]

Data Test & Hasil Sebenarnya : 
[[5.1 3.5 1.4 0.2 'setosa']
 [4.9 3.0 1.4 0.2 'setosa']
 [4.7 3.2 1.3 0.2 'setosa']
 [4.6 3.1 1.5 0.2 'setosa']
 [5.0 3.6 1.4 0.2 'setosa']
 [5.4 3.9 1.7 0.4 'setosa']
 [4.6 3.4 1.4 0.3 'setosa']
 [5.0 3.4 1.5 0.2 'setosa']
 [4.4 2.9 1.4 0.2 'setosa']
 [4.9 3.1 1.5 0.1 'setosa']
 [5.4 3.7 1.5 0.2 'setosa']
 [4.8 3.4 1.6 0.2 'setosa']
 [4.8 3.0 1.4 0.1 'setosa']
 [4.3 3.0 1.1 0.1 'setosa']
 [5.8 4.0 1.2 0.2 'setosa']]

Hasil Error :  0.0


Eksperimen  2  : 

Hasil K-NN : 
[['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10']
 ['setosa' '10